Update crud-cheat-sheet.md
Laravel-Backpack/docs pull request #209
Opened 2020-12-04 23:08 UTC by pxpm

2020-12-05 16:50 UTC, promatik requested changes

2020-12-05 16:50 UTC, promatik commented on 4.1/crud-cheat-sheet.md
> +
```suggestion
// you can define the default page length. If it does not exist we will add it to the pagination array.
$this->crud->setDefaultPageLength(10);

// you can configure the paginator shown to the user in various ways

// values and labels, 1st array the values, 2nd array the labels:
$this->crud->setPageLengthMenu([[100, 200, 300], ['one hundred', 'two hundred', 'three hundred']]); 

// values and labels in one array:
$this->crud->setPageLengthMenu([100 => 'one hundred', 200 => 'two hundred', 300 => 'three hundred']); 

// only values, we will use the values as labels:
$this->crud->setPageLengthMenu([100, 200, 300]); // OR
$this->crud->setPageLengthMenu([[100, 200, 300]]); 

// only one option available:
$this->crud->setPageLengthMenu(10); 
```

Added missing spaces and typo fix.

2020-12-08 20:05 UTC, tabacitu commented
Note to self: this should only be merged when we merge and tag https://github.com/Laravel-Backpack/CRUD/pull/3332

2020-12-08 20:15 UTC, promatik approved these changes

2021-01-11 13:38 UTC, merged