Set image attribute when creating new class object
Laravel-Backpack/docs pull request #246
Opened 2021-04-02 15:27 UTC by MerdanDev

I had problem with SQL error, that image attribute doesn't have default value when seeding my my table. For example:
$obj = new \App\Models\Product();
$obj->name = 'name';
$obj->image = 'image path';
$obj->save();

2021-04-08 06:52 UTC, tabacitu commented
Haha very nifty @MerdanDev , I like it. 
Indeed, I see no reason why this shouldn't also support adding images by path. 

@pxpm / @promatik do you guys foresee any problems with this? I don't.

2021-04-21 22:53 UTC, promatik commented on 4.1/crud-fields.md
> +            return $this->attributes['image'] = $value;
```suggestion
            return $this->attributes[$attribute_name] = $value;
```

2021-04-21 22:59 UTC, promatik requested changes

2021-04-21 22:59 UTC, promatik commented on 4.1/crud-fields.md
> +        }
```suggestion
        else
        {
            return $this->attributes[$attribute_name] = $value;
        }
```

2021-04-21 23:00 UTC, promatik commented
I don't think this will bring any trouble for us, at least I've been using this on my `trait SaveMedia` for a long time 😅

![image](https://user-images.githubusercontent.com/1838187/115631050-ffae3f80-a2fc-11eb-8f5f-6c52939af417.png)

2021-04-21 23:04 UTC, promatik commented on 4.1/crud-fields.md
> +        }
Hi @MerdanDev, thank you for this suggestion, I approve it 👌
I have just this small changes to apply, and I see you've deleted the repo from your side, so I cannot apply the changes 😅, can you please try to somehow recover it?

2021-04-27 14:31 UTC, merged