add docs for google map field
Laravel-Backpack/docs pull request #377
Opened 2022-09-23 16:53 UTC by pxpm

2022-09-27 08:37 UTC, tabacitu commented
Pedro let's please update the docs, so that "saving in two inputs" teaches devs to use Field Events, rather than hidden fields.

2022-11-28 12:53 UTC, jorgetwgroup commented
Look ready documentation.

Cheers

2022-12-13 19:40 UTC, tabacitu commented on 5.x/crud-fields.md
> +### google_map
I don't think this should be under FREE fields 👀 It's a PRO field, isn't it?

2022-12-13 19:51 UTC, tabacitu requested changes

2022-12-13 19:51 UTC, tabacitu commented on 5.x/crud-fields.md
> +Input preview:
Let's upload an image for it here, inside the Github conversation. 
Then we can take that URL and introduce it in the markdown 😉

2022-12-13 19:51 UTC, tabacitu commented on 5.x/crud-fields.md
> +             JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_THROW_ON_ERROR),
This looks weird to me on a separate line
```suggestion
            ], JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_THROW_ON_ERROR),
```

2022-12-13 19:51 UTC, tabacitu commented on 5.x/crud-fields.md
> +        }
If the getter is using arrow functions, shouldn't the setter too? Let's choose one and stick with it.

2022-12-13 19:51 UTC, tabacitu commented on 5.x/crud-fields.md
> +Uses the Google Places API to generate a Map where user can navigate and select a position to store `Latitude` (**lat**), `Longitude` (**lng**) and the address string (**formatted_address**). By defa
Sorry but no. This is NOT what the field does. Why are we writing from a technical perspective here? We should write from a USER perspective.

```suggestion
Shows a map and allows the user to navigate and select a position on that map (using the Google Places API). The field stores the latitude, longitude and the address string as a JSON in the database ( eg. `{lat: 123, lng: 456, formatted_address: 'Lisbon, Portugal'}`). If you want to save the info in separate db columns, continue reading below.
```

2022-12-13 19:51 UTC, tabacitu commented on 5.x/crud-fields.md
> +**Note**: If you want two save in separate fields continue reading below.
```suggestion
```

2022-12-18 11:45 UTC, tabacitu commented
Can I just say I absolutely LOVE the fact that @pxpm chose Lisbon for the screenshot location? Just like Jorge chose Chile for the `phone` field 😀 I love that these fields have a nod to its creator 😉 👏👏👏

2022-12-27 19:02 UTC, merged