Add URL Column
Laravel-Backpack/docs pull request #410
Opened 2023-02-11 09:02 UTC by EGYWEB-Mohamed

Add URL Column Details

2023-03-02 11:08 UTC, pxpm commented on 5.x/crud-columns.md
> +The text column will just output the url value of a db column. Its definition is:
```suggestion
The `url` column will just output the url value of a db column. Its definition is:
```

2023-03-02 11:10 UTC, pxpm requested changes
Thanks for the PR @EGYWEB-Mohamed 

Can you please just move the `url` column docs you created after the `textarea` so it stays "first letter alphabetically ordered" ? 

Thanks

2023-03-02 12:30 UTC, EGYWEB-Mohamed commented
@pxpm Done, please notice this doc in favour of this pull request : https://github.com/Laravel-Backpack/CRUD/pull/4925

2023-06-02 10:58 UTC, karandatwani92 commented
This will be available for backpack v6

2023-06-02 10:58 UTC, closed without merging