review
Laravel-Backpack/docs pull request #582
Opened 2024-05-28 16:25 UTC by pxpm

Hey @karandatwani92 

What you think about this docs structure ?

2024-05-28 16:28 UTC, karandatwani92 commented on 6.x/crud-buttons.md
> +// optinal ajax configuration
~~optinal~~ optional

2024-05-28 16:31 UTC, karandatwani92 commented on 6.x/crud-buttons.md
> +    'refreshCrudTable' => false, // should the crud table be refreshed after a successful request ?
We should comment `refreshCrudTable`. In between copy-paste, people may miss disabling this.

2024-05-28 17:00 UTC, karandatwani92 requested changes

2024-05-29 09:50 UTC, pxpm commented on 6.x/crud-buttons.md
> +```php
Agreed. 👍 Just changed it.

2024-05-29 09:50 UTC, merged